-- Q1. What is the total sales revenue generated by each product?

SELECT 
    p.product_id,
    p.product_name,
    SUM(p.price) AS total_revenue
FROM sales s
JOIN product p
ON s.product_id = p.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_revenue DESC;

-- Q2. Which 3 product has the highest sales revenue?

SELECT 
    p.product_id,
    p.product_name,
    SUM(p.price) AS total_revenue
FROM sales s
LEFT JOIN product p
ON s.product_id = p.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_revenue DESC
LIMIT 3;

-- Q3. How many users have signed up for the service and has taken the gold membership?

SELECT COUNT(*) AS users
FROM users;

SELECT COUNT(*) AS gold_users_count
FROM goldusers_signup;

-- Q4. What is the revenue generated from gold users?

SELECT
	gu.user_id, sum(price) AS total_revenue
FROM goldusers_signup gu
LEFT JOIN sales s
ON gu.user_id = s.user_id
LEFT JOIN product p
ON p.product_id = s.product_id
GROUP BY gu.user_id
ORDER BY total_revenue DESC;

-- Q5. What is the total revenue generated from gold users?

SELECT
	sum(price) AS total_revenue
FROM goldusers_signup gu
LEFT JOIN sales s
ON gu.user_id = s.user_id
LEFT JOIN product p
ON p.product_id = s.product_id
ORDER BY total_revenue DESC;

-- Q6. Which users has been a gold user for the How much of time?

SELECT
	goldusers_signup.user_id,
    user_name.user_name,
    gold_signup_date,
    datediff(curdate(), gold_signup_date) AS days_as_gold_members
FROM goldusers_signup LEFT JOIN user_name
ON user_name.user_id = goldusers_signup.user_id;

-- Q7. What is the most popular product among gold users?

SELECT 
    p.product_name,
    COUNT(*) AS order_count
FROM goldusers_signup gu 
JOIN sales s
    ON gu.user_id = s.user_id 
JOIN product p
    ON p.product_id = s.product_id
WHERE s.created_date >= gu.gold_signup_date
GROUP BY p.product_name
ORDER BY order_count DESC
LIMIT 1;

-- Q8. What is the total sales revenue generated in each year?

SELECT
    YEAR(s.created_date) AS year,
    SUM(p.price) AS total_revenue
FROM sales s
JOIN product p
    ON s.product_id = p.product_id
GROUP BY YEAR(s.created_date)
ORDER BY year ASC;

-- Q9. How has the sales revenue changed over the years?

SELECT
    year,
    total_revenue AS current_year_revenue,
    LAG(total_revenue) OVER(ORDER BY year) AS previous_year_revenue,
    ROUND(
        (total_revenue - LAG(total_revenue) OVER(ORDER BY year)) * 100.0 
        / LAG(total_revenue) OVER(ORDER BY year), 
    2) AS percentage_change

FROM (
    SELECT
        YEAR(s.created_date) AS year,
        SUM(p.price) AS total_revenue
    FROM sales s
    JOIN product p
        ON s.product_id = p.product_id
    GROUP BY YEAR(s.created_date)
) t;

-- OR with CTE

WITH revenue_cte AS (
    SELECT
        YEAR(s.created_date) AS year,
        SUM(p.price) AS total_revenue
    FROM sales s
    JOIN product p
        ON s.product_id = p.product_id
    GROUP BY YEAR(s.created_date)
)
SELECT
    year,
    total_revenue,
    LAG(total_revenue) OVER (ORDER BY year) AS previous_year_revenue,
    total_revenue - LAG(total_revenue) OVER (ORDER BY year) AS revenue_change,
    ROUND(
        (total_revenue - LAG(total_revenue) OVER (ORDER BY year)) * 100.0 /
        LAG(total_revenue) OVER (ORDER BY year),
    2) AS percentage_change
FROM revenue_cte;

-- Q10. What is the average Gold-signup compare to just sign up for the users?

SELECT
    ROUND(
        COUNT(DISTINCT g.user_id) * 100.0 / COUNT(DISTINCT u.user_id),
    2) AS gold_user_percentage
FROM users u
LEFT JOIN goldusers_signup g
ON u.user_id = g.user_id;

-- Q11. How many gold members users have order how many numbers of time ?

SELECT
	g.user_id AS gold_user_id,
    COUNT(*) AS order_count
FROM goldusers_signup g JOIN sales s
ON g.user_id = s.user_id
WHERE created_date >= gold_signup_date
GROUP BY g.user_id;

-- Q12. What is the total amount each customer spend on Online Food Delivery?

SELECT
	s.user_id,
    SUM(p.price) AS total_spent
FROM sales s LEFT JOIN product p
ON s.product_id = p.product_id
GROUP BY s.user_id
ORDER BY total_spent DESC;

-- Q13. What is the frequency of customer visits to the online platform?

SELECT
    user_id,
    COUNT(DISTINCT created_date) AS visit_frequency
FROM sales
GROUP BY user_id
ORDER BY visit_frequency DESC;

-- Q14. What was the first order purchase by each customer ?

WITH rankcte as (
SELECT
	user_id,
    product_name,
    row_number() OVER(PARTITION BY user_id ORDER BY created_date) AS rnk
FROM sales s LEFT JOIN product p
ON s.product_id = p.product_id
)

SELECT user_id, product_name FROM rankcte
WHERE rnk = 1;

-- Q15. What is the most purchase item on the menu and how many times was it purchased by all customers?

SELECT
	s.product_id,
    product_name,
    COUNT(created_date) AS order_count
FROM sales s LEFT JOIN product p
ON s.product_id = p.product_id
GROUP BY product_id, product_name
ORDER BY order_count DESC
LIMIT 1;

-- Q16. Which item was most popular for each customer ?
WITH product_count AS
(
SELECT
        s.user_id,
        p.product_name,
        COUNT(*) AS order_count
    FROM sales s
    JOIN product p
        ON s.product_id = p.product_id
    GROUP BY s.user_id, p.product_name
),
ranked_products AS
(
SELECT
	*,
    row_number() OVER(PARTITION BY user_id ORDER BY order_count DESC) AS rnk
FROM product_count
)

SELECT user_id, product_name, order_count FROM ranked_products WHERE rnk = 1;

-- Q17. Which item was purchase first by the customer after they become a member ?
WITH cte AS
(
SELECT
	g.user_id,
    created_date,
    p.product_id,
    p.product_name
FROM goldusers_signup g JOIN sales s
ON g.user_id = s.user_id
LEFT JOIN product p
ON p.product_id = s.product_id
WHERE created_date >= gold_signup_date
),
cte2 AS
(
SELECT
	*,
    row_number() OVER(PARTITION BY user_id ORDER BY created_date) AS rnk
FROM cte
)

SELECT * FROM cte2
WHERE rnk = 1;

-- Q18.Which item was purchase before the customer become a member ?

WITH cte AS
(
SELECT
	g.user_id,
    created_date,
    p.product_id,
    p.product_name
FROM goldusers_signup g JOIN sales s
ON g.user_id = s.user_id
LEFT JOIN product p
ON p.product_id = s.product_id
WHERE created_date < gold_signup_date
),

cte2 AS
(
SELECT *,
	ROW_NUMBER() OVER(PARTITION BY user_id ORDER BY created_date DESC) AS rnk
FROM cte
)

SELECT * FROM cte2
WHERE rnk = 1;

-- Q19. What is the total orders and amount spent for each member before they become a member ?

SELECT
	g.user_id,
    COUNT(created_date) AS order_count,
    SUM(price) AS amount_spent
FROM goldusers_signup g LEFT JOIN sales s
ON g.user_id = s.user_id
LEFT JOIN product p ON p.product_id = s.product_id
WHERE created_date < gold_signup_date
GROUP BY g.user_id
ORDER BY amount_spent DESC;

-- Q20. Rank all the transactions for each member whenever they are a XYZ gold member for every non gold member Transaction marks as na ?

SELECT
    user_id,
    created_date,
    product_id,
    
    CASE 
        WHEN transaction_rank IS NULL THEN 'NA'
        ELSE CAST(transaction_rank AS CHAR)
    END AS transaction_rank

FROM (
    SELECT
        s.user_id,
        s.created_date,
        s.product_id,
        
        CASE 
            WHEN s.created_date >= g.gold_signup_date 
            THEN ROW_NUMBER() OVER (
                PARTITION BY s.user_id 
                ORDER BY s.created_date
            )
        END AS transaction_rank

    FROM sales s
    LEFT JOIN goldusers_signup g
        ON s.user_id = g.user_id
) t;
